#!perl
# Time-stamp: Thu Oct 29 06:00 PM 2009 E

##################
#
# This file was automatically generated by ZooZ.pl v1.2
# on Fri Aug 15 15:34:53 2008.
#
##################

#
# Headers
#
use strict;
use warnings;

use Tk 804;
require Tk::ROText;
require "ctime.pl";

#
# Global variables
#
my (
     # MainWindow
     $MW,

     # Hash of all widgets
     %ZWIDGETS,
    );

#
# User-defined variables (if any)
#

######################
#
# Create the MainWindow
#
######################

$MW = MainWindow->new;

######################
#
# Load any images and fonts
#
######################
ZloadImages();
ZloadFonts ();

# Widget Entry1 isa Entry
$ZWIDGETS{'StartTm'} = $MW->Entry()->grid(
   -row        => 0,
   -column     => 0,
   -columnspan => 1,
   -sticky     => 'ew',
  );

$ZWIDGETS{'EndTm'} = $MW->Entry()->grid(
   -row        => 0,
   -column     => 1,
   -columnspan => 1,
   -sticky     => 'ew',
  );

# Widget Leaving isa Button
$ZWIDGETS{'Calc'} = $MW->Button(
   -command => \&CalcTime,
   -text    => 'Calc',
  )->grid(
   -row        => 0,
   -column     => 2,
   -columnspan => 1,
  );

# Widget Leaving isa Button
$ZWIDGETS{'Exit'} = $MW->Button(
   -command => sub { exit },
   -text    => 'Exit',
  )->grid(
   -row        => 0,
   -column     => 3,
   -columnspan => 1,
  );

# Widget Log isa ROText
$ZWIDGETS{'Log'} = $MW->ROText()->grid(
   -row        => 1,
   -column     => 0,
   -rowspan    => 7,
   -columnspan => 4,
  );

#tie *LOG, 'Tk::ROText', $ZWIDGETS{'Log'};

my $logFile = "timeDiffTk.Log";

#if (open IN, "$logFile")
#{
#    while (<IN>)
#    {
#	$ZWIDGETS{'Log'}->insert("1.0", $_);
#    }
#    close IN;
#}

open LOGFILE, ">>$logFile";
my $fh = select(LOGFILE);
$| = 1;
select($fh);

###############
#
# MainLoop
#
###############

$ZWIDGETS{'Log'}->insert("end", "Directions:\n");
$ZWIDGETS{'Log'}->insert("end", "   1) In the left  entry box above put start time (use 24hr time).\n");
$ZWIDGETS{'Log'}->insert("end", "   2) In the right entry box above put end   time (use 24hr time).\n");
$ZWIDGETS{'Log'}->insert("end", "   3) Select the \"Calc\" button and answer will appear below.\n\n");

MainLoop;

#######################
#
# Subroutines
#
#######################

sub ZloadImages {
}

sub ZloadFonts {
}

sub CalcTime {
    my ($hr, $min, $sec) = (0, 0, 0);

    my $endTm  = $ZWIDGETS{'EndTm'}->get();
    ($hr, $min, $sec) = split(/:/, $endTm);

    my $endTotal = ($hr * 3600) + ($min * 60) + $sec;
print "\nEnd total seconds: $endTotal\n\n";

    my $startTm  = $ZWIDGETS{'StartTm'}->get();
    ($hr, $min, $sec) = split(/:/, $startTm);

    my $startTotal = ($hr * 3600) + ($min * 60) + $sec;

print "\nStart total seconds: $startTotal\n";

    my $diff  = $endTotal - $startTotal;

printf "\nDifferance seconds = %ld\n\n", $diff;

    $hr  = $diff / 3600;

    $min = ($diff % 3600) / 60;

    $sec = ($diff % 60);

    my $str = sprintf("$endTm - $startTm = %2ld:%02ld:%02ld\n", $hr, $min, $sec);
    my $t = ctime(time);
    chomp($t);
    print LOGFILE "$t: $str";
    $ZWIDGETS{'Log'}->insert("end", $str);
}


